export const ProductService = {
  getProductsData() {
    return [
      {
        id: "1000",
        code: "f230fh0g3",
        name: "AJANTHA FARMA USA INC. -URP",
        description: "Invoice",
        image: "bamboo-watch.jpg",
        price: 65,
        category: "Accessories",
        quantity: 24,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1001",
        code: "nvklal433",
        name: "Black Watch",
        description: "Invoice",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        name: "Blue Band",
        description: "Invoice",
        image: "blue-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 2,
        inventoryStatus: "Rejected",
        rating: 3,
      },
      {
        id: "1003",
        code: "244wgerg2",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032CIZZ",
        description: "Invoice",
        image: "blue-t-shirt.jpg",
        price: 29,
        category: "Clothing",
        quantity: 25,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1004",
        code: "h456wer53",
        name: "Bracelet",
        description: "Invoice",
        image: "bracelet.jpg",
        price: 15,
        category: "Accessories",
        quantity: 73,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1005",
        code: "av2231fwg",
        name: "Brown Purse",
        description: "Invoice",
        image: "brown-purse.jpg",
        price: 120,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "Error",
        rating: 4,
      },
      {
        id: "1006",
        code: "bib36pfvm",
        name: "Chakra Bracelet",
        description: "Invoice",
        image: "chakra-bracelet.jpg",
        price: 32,
        category: "Accessories",
        quantity: 5,
        inventoryStatus: "Rejected",
        rating: 3,
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        name: "Galaxy Earrings",
        description: "Invoice",
        image: "galaxy-earrings.jpg",
        price: 34,
        category: "Accessories",
        quantity: 23,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1008",
        code: "vbb124btr",
        name: "Game Controller",
        description: "Invoice",
        image: "game-controller.jpg",
        price: 99,
        category: "Electronics",
        quantity: 2,
        inventoryStatus: "Rejected",
        rating: 4,
      },
      {
        id: "1009",
        code: "cm230f032",
        name: "Gaming Set",
        description: "Invoice",
        image: "gaming-set.jpg",
        price: 299,
        category: "Electronics",
        quantity: 63,
        inventoryStatus: "Success",
        rating: 3,
      },
      {
        id: "1010",
        code: "plb34234v",
        name: "Gold Phone Case",
        description: "Invoice",
        image: "gold-phone-case.jpg",
        price: 24,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "Error",
        rating: 4,
      },
      {
        id: "1011",
        code: "4920nnc2d",
        name: "Green Earbuds",
        description: "Invoice",
        image: "green-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 23,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1012",
        code: "250vm23cc",
        name: "Green T-Shirt",
        description: "Invoice",
        image: "green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 74,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1013",
        code: "fldsmn31b",
        name: "Grey T-Shirt",
        description: "Invoice",
        image: "grey-t-shirt.jpg",
        price: 48,
        category: "Clothing",
        quantity: 0,
        inventoryStatus: "Error",
        rating: 3,
      },
      {
        id: "1014",
        code: "waas1x2as",
        name: "Headphones",
        description: "Invoice",
        image: "headphones.jpg",
        price: 175,
        category: "Electronics",
        quantity: 8,
        inventoryStatus: "Rejected",
        rating: 5,
      },
      {
        id: "1015",
        code: "vb34btbg5",
        name: "Light Green T-Shirt",
        description: "Invoice",
        image: "light-green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 34,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1016",
        code: "k8l6j58jl",
        name: "Lime Band",
        description: "Invoice",
        image: "lime-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 12,
        inventoryStatus: "Success",
        rating: 3,
      },
      {
        id: "1017",
        code: "v435nn85n",
        name: "Mini Speakers",
        description: "Invoice",
        image: "mini-speakers.jpg",
        price: 85,
        category: "Clothing",
        quantity: 42,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1018",
        code: "09zx9c0zc",
        name: "Painted Phone Case",
        description: "Invoice",
        image: "painted-phone-case.jpg",
        price: 56,
        category: "Accessories",
        quantity: 41,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1019",
        code: "mnb5mb2m5",
        name: "Pink Band",
        description: "Invoice",
        image: "pink-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 63,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1020",
        code: "r23fwf2w3",
        name: "Pink Purse",
        description: "Invoice",
        image: "pink-purse.jpg",
        price: 110,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "Error",
        rating: 4,
      },
      {
        id: "1021",
        code: "pxpzczo23",
        name: "Purple Band",
        description: "Invoice",
        image: "purple-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 6,
        inventoryStatus: "Rejected",
        rating: 3,
      },
      {
        id: "1022",
        code: "2c42cb5cb",
        name: "Purple Gemstone Necklace",
        description: "Invoice",
        image: "purple-gemstone-necklace.jpg",
        price: 45,
        category: "Accessories",
        quantity: 62,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1023",
        code: "5k43kkk23",
        name: "Purple T-Shirt",
        description: "Invoice",
        image: "purple-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 2,
        inventoryStatus: "Rejected",
        rating: 5,
      },
      {
        id: "1024",
        code: "lm2tny2k4",
        name: "Shoes",
        description: "Invoice",
        image: "shoes.jpg",
        price: 64,
        category: "Clothing",
        quantity: 0,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1025",
        code: "nbm5mv45n",
        name: "Sneakers",
        description: "Invoice",
        image: "sneakers.jpg",
        price: 78,
        category: "Clothing",
        quantity: 52,
        inventoryStatus: "Success",
        rating: 4,
      },
      {
        id: "1026",
        code: "zx23zc42c",
        name: "Teal T-Shirt",
        description: "Invoice",
        image: "teal-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 3,
        inventoryStatus: "Rejected",
        rating: 3,
      },
      {
        id: "1027",
        code: "acvx872gc",
        name: "Yellow Earbuds",
        description: "Invoice",
        image: "yellow-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 35,
        inventoryStatus: "Success",
        rating: 3,
      },
      {
        id: "1028",
        code: "tx125ck42",
        name: "Yoga Mat",
        description: "Invoice",
        image: "yoga-mat.jpg",
        price: 20,
        category: "Fitness",
        quantity: 15,
        inventoryStatus: "Success",
        rating: 5,
      },
      {
        id: "1029",
        code: "gwuby345v",
        name: "Yoga Set",
        description: "Invoice",
        image: "yoga-set.jpg",
        price: 20,
        category: "Fitness",
        quantity: 25,
        inventoryStatus: "Success",
        rating: 8,
      },
    ];
  },

  getProductsWithOrdersData() {
    return [
      {
        id: "1000",
        code: "f230fh0g3",
        name: "AJANATA PHARMA USA INC. -URP",
        description: "Invoice",
        image: "bamboo-watch.jpg",
        docNumber: "978-0-292-99197-0",
        price: 7697,
        category: "01-Jan-2024",
        generatedOn: "01-Jan-2024",
        quantity: 24,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: "978-0-292-99197-",
        orders: [
          {
            id: "1000-0",
            productCode: "f230fh0g3",
            date: "2020-09-13",
            amount: 65,
            quantity: 1,
            customer: "David James",
            status: "PENDING",
          },
          {
            id: "1000-1",
            productCode: "f230fh0g3",
            date: "2020-05-14",
            amount: 130,
            quantity: 2,
            customer: "Leon Rodrigues",
            status: "DELIVERED",
          },
          {
            id: "1000-2",
            productCode: "f230fh0g3",
            date: "2019-01-04",
            amount: 65,
            quantity: 1,
            customer: "Juan Alejandro",
            status: "RETURNED",
          },
          {
            id: "1000-3",
            productCode: "f230fh0g3",
            date: "2020-09-13",
            amount: 195,
            quantity: 3,
            customer: "Claire Morrow",
            status: "CANCELLED",
          },
        ],
      },
      {
        id: "1001",
        code: "nvklal433",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032C1ZZ",
        description: "Invoice",
        image: "black-watch.jpg",
        docNumber: "978-0-292-99197-1",
        price: 7695,
        category: "05-Jan-2024",
        generatedOn: "01-Jan-2024",
        quantity: 61,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: "978-0-292-99197-1",
        orders: [
          {
            id: "1001-0",
            productCode: "nvklal433",
            date: "2020-05-14",
            amount: 72,
            quantity: 1,
            customer: "Maisha Jefferson",
            status: "DELIVERED",
          },
          {
            id: "1001-1",
            productCode: "nvklal433",
            date: "2020-02-28",
            amount: 144,
            quantity: 2,
            customer: "Octavia Murillo",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032C1ZZ",
        description: "Invoice",
        image: "blue-band.jpg",
        docNumber: 978-0-292-99197-2,
        price: 99197,
        category: "04-Jan-2024",
        generatedOn: "07-Jan-2024",
        quantity: 2,
        inventoryStatus: "Rejected",
        invoiceType: "B2B",
        rating: "978-0-292-99197-2",
        orders: [
          {
            id: "1002-0",
            productCode: "zz21cz3c1",
            date: "2020-07-05",
            amount: 79,
            quantity: 1,
            customer: "Stacey Leja",
            status: "DELIVERED",
          },
          {
            id: "1002-1",
            productCode: "zz21cz3c1",
            date: "2020-02-06",
            amount: 79,
            quantity: 1,
            customer: "Ashley Wickens",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1003",
        code: "244wgerg2",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032CIZZ",
        description: "Invoice",
        image: "blue-t-shirt.jpg",
        docNumber: 978-0-292-9197-2,
        price: 29,
        category: "11-Jan-2024",
        generatedOn: "11-Jan-2024",
        quantity: 25,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: 5,
        orders: [],
      },
      {
        id: "1004",
        code: "h456wer53",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032C1ZZ",
        description: "Invoice",
        image: "bracelet.jpg",
        docNumber: 974-0-292-99197-2,
        price: 15,
        category: "13-Jan-2024",
        generatedOn: "21-Jan-2024",
        quantity: 73,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: 4,
        orders: [
          {
            id: "1004-0",
            productCode: "h456wer53",
            date: "2020-09-05",
            amount: 60,
            quantity: 4,
            customer: "Mayumi Misaki",
            status: "PENDING",
          },
          {
            id: "1004-1",
            productCode: "h456wer53",
            date: "2019-04-16",
            amount: 2,
            quantity: 30,
            customer: "Francesco Salvatore",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1005",
        code: "av2231fwg",
        name: "Brown Purse",
        description: "Invoice",
        image: "brown-purse.jpg",
        docNumber: 978-0-292-99191-2,
        price: 120,
        category: "14-Jan-2024",
        generatedOn: "03-Jan-2024",
        quantity: 0,
        inventoryStatus: "Error",
        invoiceType: "B2B",
        rating: 4,
        orders: [
          {
            id: "1005-0",
            productCode: "av2231fwg",
            date: "2020-01-25",
            amount: 120,
            quantity: 1,
            customer: "Isabel Sinclair",
            status: "RETURNED",
          },
          {
            id: "1005-1",
            productCode: "av2231fwg",
            date: "2019-03-12",
            amount: 240,
            quantity: 2,
            customer: "Lionel Clifford",
            status: "DELIVERED",
          },
          {
            id: "1005-2",
            productCode: "av2231fwg",
            date: "2019-05-05",
            amount: 120,
            quantity: 1,
            customer: "Cody Chavez",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1006",
        code: "bib36pfvm",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AAFCI5032CIZZ",
        description: "Invoice",
        image: "chakra-bracelet.jpg",
        docNumber: 978-0-292-99147-2,
        price: 32,
        category: "01-Feb-2024",
        generatedOn: "31-Jan-2024",
        quantity: 5,
        invoiceType: "B2B",
        inventoryStatus: "Rejected",
        rating: 3,
        orders: [
          {
            id: "1006-0",
            productCode: "bib36pfvm",
            date: "2020-02-24",
            amount: 32,
            quantity: 1,
            customer: "Arvin Darci",
            status: "DELIVERED",
          },
          {
            id: "1006-1",
            productCode: "bib36pfvm",
            date: "2020-01-14",
            amount: 64,
            quantity: 2,
            customer: "Izzy Jones",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 27AFCI5032CIZZ",
        description: "Invoice",
        image: "galaxy-earrings.jpg",
        docNumber: 978-0-292-99197-9,
        price: 34,
        category: "03-Feb-2024",
        generatedOn: "22-Jan-2024",
        quantity: 23,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: 5,
        orders: [
          {
            id: "1007-0",
            productCode: "mbvjkgip5",
            date: "2020-06-19",
            amount: 34,
            quantity: 1,
            customer: "Jennifer Smith",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1008",
        code: "vbb124btr",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - 2AAFCI5032CIZZ",
        description: "Invoice",
        image: "game-controller.jpg",
        price: 99,
        category: "01-Jan-2024",
        generatedOn: "16-Mar-2024",
        quantity: 2,
        inventoryStatus: "Rejected",
        invoiceType: "B2B",
        rating: 4,
        orders: [
          {
            id: "1008-0",
            productCode: "vbb124btr",
            date: "2020-01-05",
            amount: 99,
            quantity: 1,
            customer: "Jeanfrancois David",
            status: "DELIVERED",
          },
          {
            id: "1008-1",
            productCode: "vbb124btr",
            date: "2020-01-19",
            amount: 198,
            quantity: 2,
            customer: "Ivar Greenwood",
            status: "RETURNED",
          },
        ],
      },
      {
        id: "1009",
        code: "cm230f032",
        name: "IRIS LOGIX SOLUTIONS PRIVATE LIMITED - AAFCI5032CIZZ",
        description: "Invoice",
        image: "gaming-set.jpg",
        docNumber: 978-0-292-99197-0,
        price: 299,
        category: "01-Apr-2024",
        generatedOn: "23-Jan-2024",
        quantity: 63,
        inventoryStatus: "Success",
        invoiceType: "B2B",
        rating: 3,
        orders: [
          {
            id: "1009-0",
            productCode: "cm230f032",
            date: "2020-06-24",
            amount: 299,
            quantity: 1,
            customer: "Kadeem Mujtaba",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1010",
        code: "plb34234v",
        name: "Gold Phone Case",
        description: "Invoice",
        image: "gold-phone-case.jpg",
        docNumber: 978-0-392-99197-2,
        price: 24,
        category: "01-May-2024",
        generatedOn: "15-Jan-2024",
        quantity: 0,
        invoiceType: "B2B",
        inventoryStatus: "Error",
        rating: 4,
        orders: [
          {
            id: "1010-0",
            productCode: "plb34234v",
            date: "2020-02-04",
            amount: 24,
            quantity: 1,
            customer: "James Butt",
            status: "DELIVERED",
          },
          {
            id: "1010-1",
            productCode: "plb34234v",
            date: "2020-05-05",
            amount: 48,
            quantity: 2,
            customer: "Josephine Darakjy",
            status: "DELIVERED",
          },
        ],
      }
    ];
  },

  getProductsMini() {
    return Promise.resolve(this.getProductsData().slice(0, 5));
  },

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  },

  getProducts() {
    return Promise.resolve(this.getProductsData());
  },

  getProductsWithOrdersSmall() {
    return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
  },

  getProductsWithOrders() {
    return Promise.resolve(this.getProductsWithOrdersData());
  },
};
